name: Scheduled Cloud end-to-end tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  playwright-cloud:
    permissions:
      contents: read
      id-token: write
    uses: grafana/data-sources-ci-workflows/.github/workflows/playwright-cloud.yml@51ac69d43a199cee552c96fc184f15d64ea75892 # main
    secrets: inherit
    with:
      repo-secrets: |
        DS_INSTANCE_NAME=gcm:name
        DS_INSTANCE_AUTHN_TYPE=gcm:json_authenticationType
        DS_INSTANCE_DEFAULT_PROJECT=gcm:json_defaultProject
        DS_INSTANCE_CLIENT_EMAIL=gcm:json_clientEmail
        DS_INSTANCE_TOKEN_URI=gcm:json_tokenUri
        DS_INSTANCE_PRIVATE_KEY=gcm:secure_privateKey
